yolo:
  type: "yolov4_tiny"
  iou_threshold: 0.5
  score_threshold: 0.10
  max_boxes: 100
  strides: "32,16"
  anchors: "23,27 37,58 81,82 81,82 135,169 344,319"
  mask: "3,4,5 0,1,2"
  name_path: "./data/bee_dataset/beedataset_only.name"

train:
  label: "bee_yolov4_tiny"
  anno_path: "/d/hpc/home/ratkop/yolox/data/bee_dataset/labels/labels_scaled/bee_train.txt"
  image_size: "416"

  batch_size: 1 
  init_weight_path: "/d/hpc/home/ratkop/yolox/ckpts/yolov4-tiny-pollenDetect-0.3186.h5"
  save_weight_path: "/d/hpc/home/ratkop/yolox/ckpts"

  loss_type: "CIoU+FL"

  mosaic: true
  label_smoothing: true
  normal_method: true

  ignore_threshold: 0.3 
# 0.5 -> gives conv2d loss nan 
test:
  anno_path: "/d/hpc/home/ratkop/yolox/data/bee_dataset/labels/labels_scaled/bee_test.txt"
  image_size: "416"
  batch_size: 1
  init_weight_path: "/d/hpc/home/ratkop/yolox/ckpts/yolov4-tiny.h5"